# AiKv Cluster Monitor

services:
  aikv-exporter-replica-1:
    image: oliver006/redis_exporter:v1.80.1
    container_name: aikv-exporter-replica-1
    environment:
      - REDIS_ADDR=redis://aikv-replica-1:6379
    ports:
      - "9221:9121"
    restart: unless-stopped
    networks:
      - aikv-workflow

  aidb-exporter-replica-1:
    image: aidb-exporter:v0.0.2
    container_name: aidb-exporter-replica-1
    environment:
      - AIDB_TARGET=redis://aikv-replica-1:6379
      - EXPORTER_PORT=9120
    ports:
      - "9220:9120"
    restart: unless-stopped
    networks:
      - aikv-workflow

  aikv-exporter-master-2:
    image: oliver006/redis_exporter:v1.80.1
    container_name: aikv-exporter-master-2
    environment:
      - REDIS_ADDR=redis://aikv-master-2:6379
    ports:
      - "9321:9121"
    restart: unless-stopped
    networks:
      - aikv-workflow

  aidb-exporter-master-2:
    image: aidb-exporter:v0.0.2
    container_name: aidb-exporter-master-2
    environment:
      - AIDB_TARGET=redis://aikv-master-2:6379
      - EXPORTER_PORT=9120
    ports:
      - "9320:9120"
    restart: unless-stopped
    networks:
      - aikv-workflow

  aikv-exporter-replica-2:
    image: oliver006/redis_exporter:v1.80.1
    container_name: aikv-exporter-replica-2
    environment:
      - REDIS_ADDR=redis://aikv-replica-2:6379
    ports:
      - "9421:9121"
    restart: unless-stopped
    networks:
      - aikv-workflow

  aidb-exporter-replica-2:
    image: aidb-exporter:v0.0.2
    container_name: aidb-exporter-replica-2
    environment:
      - AIDB_TARGET=redis://aikv-replica-2:6379
      - EXPORTER_PORT=9120
    ports:
      - "9420:9120"
    restart: unless-stopped
    networks:
      - aikv-workflow

  aikv-exporter-master-3:
    image: oliver006/redis_exporter:v1.80.1
    container_name: aikv-exporter-master-3
    environment:
      - REDIS_ADDR=redis://aikv-master-3:6379
    ports:
      - "9521:9121"
    restart: unless-stopped
    networks:
      - aikv-workflow

  aidb-exporter-master-3:
    image: aidb-exporter:v0.0.2
    container_name: aidb-exporter-master-3
    environment:
      - AIDB_TARGET=redis://aikv-master-3:6379
      - EXPORTER_PORT=9120
    ports:
      - "9520:9120"
    restart: unless-stopped
    networks:
      - aikv-workflow

  aikv-exporter-replica-3:
    image: oliver006/redis_exporter:v1.80.1
    container_name: aikv-exporter-replica-3
    environment:
      - REDIS_ADDR=redis://aikv-replica-3:6379
    ports:
      - "9621:9121"
    restart: unless-stopped
    networks:
      - aikv-workflow

  aidb-exporter-replica-3:
    image: aidb-exporter:v0.0.2
    container_name: aidb-exporter-replica-3
    environment:
      - AIDB_TARGET=redis://aikv-replica-3:6379
      - EXPORTER_PORT=9120
    ports:
      - "9620:9120"
    restart: unless-stopped
    networks:
      - aikv-workflow

networks:
  aikv-workflow:
    name: aikv-workflow
    driver: bridge