global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["${SERVER_HOST}:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["${SERVER_HOST}:8088"]

  - job_name: "aikv-exporter"
    static_configs:
      - targets: ["${MONITOR_HOST}:9121"]

  - job_name: "aidb-exporter"
    static_configs:
      - targets: ["${MONITOR_HOST}:9120"]

  - job_name: "aikv-cluster-exporter"
    static_configs:
      - targets: ["${MONITOR_HOST}:9121"]
        labels:
          node: master-1
      - targets: ["${MONITOR_HOST}:9221"]
        labels:
          node: replica-1a
      - targets: ["${MONITOR_HOST}:9321"]
        labels:
          node: replica-1b
      - targets: ["${MONITOR_HOST}:9421"]
        labels:
          node: master-2
      - targets: ["${MONITOR_HOST}:9521"]
        labels:
          node: replica-2a
      - targets: ["${MONITOR_HOST}:9621"]
        labels:
          node: replica-2b
      - targets: ["${MONITOR_HOST}:9721"]
        labels:
          node: master-3
    relabel_configs:
      - source_labels: [node]
        regex: (.*)
        replacement: "aikv-exporter-$1:9121"
        target_label: instance

  - job_name: "aidb-cluster-exporter"
    static_configs:
      - targets: ["${MONITOR_HOST}:9120"]
        labels:
          node: master-1
      - targets: ["${MONITOR_HOST}:9220"]
        labels:
          node: replica-1a
      - targets: ["${MONITOR_HOST}:9320"]
        labels:
          node: replica-1b
      - targets: ["${MONITOR_HOST}:9420"]
        labels:
          node: master-2
      - targets: ["${MONITOR_HOST}:9520"]
        labels:
          node: replica-2a
      - targets: ["${MONITOR_HOST}:9620"]
        labels:
          node: replica-2b
      - targets: ["${MONITOR_HOST}:9720"]
        labels:
          node: master-3
    relabel_configs:
      - source_labels: [node]
        regex: (.*)
        replacement: "aidb-exporter-$1:9120"
        target_label: instance
